[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[deploy]
numReplicas = 1
# startCommand = "go run ./server/cmd/main.go"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
