[build]
builder = "DOCKERFILE"
buildCommand = "echo building!"
dockerfilePath = "/server/Dockerfile"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"